### ISSUE TITLE
Paste don't work

### ISSUE THREAD

**Issue by jpdupont** [i07/rightClick#4]
Hello,
On my Brackets, OSX 11, "paste" in the right click menu don't paste anything ...

**Comment by i07** [comment]
Hi,

Which version of brackets are you using?

**Comment by jpdupont** [comment]
Version 1.7 édition 1.7.0-16898(release b0a363b71)
Horodatage de la version : Wed Jun 08 2016 04:20:22 GMT-0700

Thanks !

**Comment by kjw86** [comment]
Paste also doesn't work on Windows 10, Brackets Release 1.7 build 1.7.0-16898 (release b0a363b71)

**Comment by sisforserrgio** [comment]
Yes it does not work with paste. Probably brackets bug cause every plugin which add right click support fast to paste trougth Rclick.

**Comment by i07** [comment]
Hi All,

Yes, I have taken a proper look, but indeed since Chrome 43 there is no longer support for the native document.exeCommand("paste") function, which my extension uses, this does explain why it suddenly stopped working. (you can read a bit here: https://github.com/adobe/brackets/issues/10905 and on their trello board: https://trello.com/c/ZriVEu50/935-clipboard-cut-copy-paste-in-editor-context-menu, as where it's discussed on how to bring native clipboard actions back).

In the meantime, someone else created a similar rightclick copy paste extension via the use of node plugin copy-paste; since I will not try to re-invent the wheel here, it might work out to get that functionality back. ( https://github.com/jbardnz/RightClickExtended )

As for my extension, once brackets provides background access to the paste command on chromium layer I will review the code, but most likely it should work again once that has been settled (if they ever decide to do).

Thanks for using the rightClick extension for brackets.. ;) 

Cheers
